import assert from 'node:assert/strict';
import { adicionarConvidado, dataAgendada, statusPresenca, textoConvite, vagaParaJogador } from '../lib/noite';
import type { Tournament } from '../types';

async function main() {
const memory = new Map<string, string>();
Object.defineProperty(globalThis, 'window', { value: { localStorage: { getItem: (key: string) => memory.get(key) ?? null, setItem: (key: string, value: string) => memory.set(key, value), removeItem: (key: string) => memory.delete(key) } }, configurable: true });
const { useTournamentStore } = await import('../stores/tournamentStore');
await useTournamentStore.persist.rehydrate();
const agora = new Date(2026, 8, 15, 12);
assert.equal(dataAgendada('31/02/2027', '20:00', agora), null);
assert.equal(dataAgendada('16/09/2026', '24:00', agora), null);
assert.equal(dataAgendada('14/09/2026', '20:00', agora), null);
assert.equal(dataAgendada('16/09/2026', '20:00', agora), new Date(2026, 8, 16, 20).toISOString());
let t: Tournament = { id: 'night', name: 'Quarta', format: 'regular', status: 'upcoming', buyIn: 19.9, reEntryAllowed: false, maxReEntries: 0, startTime: new Date(2026, 8, 16, 20).toISOString(), blindStructure: [], currentLevel: 0, players: [], createdBy: 'me', createdAt: '', capacity: 2 };
const guest = (id: string, name: string) => ({ id, name, status: 'confirmed' as const, createdAt: id });
t = adicionarConvidado(t, guest('a', 'Ana'));
t = adicionarConvidado(t, guest('b', 'Bruno'));
assert.equal(t.players.length, 0, 'RSVP não cobra buy-in');
assert.equal(adicionarConvidado(t, guest('c', ' ana ')), t, 'nome duplicado');
t = adicionarConvidado(t, guest('c', 'Caio'));
assert.equal(t.invitees![2].status, 'waiting');
assert.equal(vagaParaJogador(t, 'Extra'), false, 'confirmados reservam as vagas');
assert.equal(vagaParaJogador(t, 'Ana'), true, 'confirmado pode ocupar sua reserva');
assert.equal(statusPresenca(t, 'confirmed', 'a'), 'confirmed', 'reconfirmar não perde vaga');
assert.equal(statusPresenca(t, 'maybe', 'c'), 'maybe');
assert.match(textoConvite(t), /Quarta/);
assert.match(textoConvite(t), /19,90/);
useTournamentStore.setState({ tournaments: [t], activeTournamentId: null });
const store = useTournamentStore.getState();
store.checkIn(t.id, 'a');
store.checkIn(t.id, 'a');
store.checkIn(t.id, 'c');
assert.equal(useTournamentStore.getState().tournaments[0].players.length, 1, 'check-in idempotente e espera não entra');
assert.equal(useTournamentStore.getState().tournaments[0].players[0].paymentStatus, 'pending');
store.eliminatePlayer(t.id, useTournamentStore.getState().tournaments[0].players[0].id);
assert.equal(useTournamentStore.getState().tournaments[0].status, 'upcoming', 'não elimina antes do início');
store.setAttendance(t.id, 'b', 'absent');
store.setAttendance(t.id, 'c', 'confirmed');
store.checkIn(t.id, 'c');
assert.equal(useTournamentStore.getState().tournaments[0].players.length, 2);
store.addPlayer(t.id, { userId: 'x', name: 'Extra', buyIns: 1, reEntries: 0, addOns: 0, paymentStatus: 'pending' });
assert.equal(useTournamentStore.getState().tournaments[0].players.length, 2, 'respeita lotação');
const p = useTournamentStore.getState().tournaments[0].players[0];
store.removePlayer(t.id, p.id);
assert.equal(useTournamentStore.getState().tournaments[0].invitees![0].playerId, undefined, 'remover entrada libera novo check-in');
store.checkIn(t.id, 'a');
await useTournamentStore.persist.rehydrate();
assert.equal(useTournamentStore.getState().tournaments[0].players.length, 2, 'entradas sobrevivem ao armazenamento');
assert.equal(useTournamentStore.getState().tournaments[0].invitees!.length, 3, 'convites sobrevivem ao armazenamento');
store.startTournament(t.id);
store.invite(t.id, 'Novo', 'confirmed');
assert.equal(useTournamentStore.getState().tournaments[0].invitees!.length, 3, 'RSVP encerrado após início');
console.log('Agendamento, presença, vagas e check-in: tudo passou.');
}
main().catch(error => { console.error(error); process.exitCode = 1; });
