import assert from 'node:assert/strict';
import { desfazerAssentos, moverAssento, podeDesfazerAssentos, sortearAssentos } from '../lib/assentos';
import { auditar } from '../lib/auditoria';
import { desfazerEliminacao, eliminar } from '../lib/torneio';
import type { Tournament } from '../types';

const t: Tournament = { id: 'seats', name: 'Mesa', format: 'regular', status: 'running', buyIn: 25, reEntryAllowed: true, maxReEntries: 2, startTime: '', blindStructure: [], currentLevel: 0, createdBy: 'me', createdAt: '', players: Array.from({ length: 13 }, (_, i) => ({ id: `p${i}`, userId: `u${i}`, name: `Jogador ${i}`, buyIns: 1, reEntries: 0, addOns: 0, paymentStatus: 'pending' })) };
const sorted = sortearAssentos(t, 6, () => 0.5);
assert.equal(new Set(sorted.players.map(p => `${p.tableNumber}:${p.seatNumber}`)).size, 13);
assert.equal(Math.max(...sorted.players.map(p => p.tableNumber!)), 3);
assert.ok(sorted.players.every(p => p.seatNumber! >= 1 && p.seatNumber! <= 6));
assert.ok(sorted.players.every(p => p.buyIns === 1 && p.paymentStatus === 'pending'));
assert.equal(sortearAssentos(t, 1), t);
const closed = { ...t, status: 'finished' as const };
assert.equal(sortearAssentos(closed, 6), closed);
const [a, b] = sorted.players;
const moved = moverAssento(sorted, a.id, b.tableNumber!, b.seatNumber!);
assert.equal(moved.players[0].seatNumber, b.seatNumber);
assert.equal(moved.players[1].seatNumber, a.seatNumber);
assert.equal(moved.players[1].tableNumber, a.tableNumber);
assert.equal(moverAssento(sorted, a.id, 999, 1), sorted);
assert.equal(moverAssento(sorted, a.id, 1, 7), sorted);
const restored = desfazerAssentos({ ...moved, players: moved.players.map(p => p.id === a.id ? { ...p, paymentStatus: 'confirmed' } : p) });
assert.equal(restored.players[0].seatNumber, a.seatNumber);
assert.equal(restored.players[0].paymentStatus, 'confirmed', 'undo não reverte pagamento');
assert.equal(podeDesfazerAssentos({ ...moved, players: moved.players.slice(1) }), false);
const withNew = moverAssento({ ...sorted, players: [...sorted.players, { ...t.players[0], id: 'new' }] }, 'new', a.tableNumber!, a.seatNumber!);
assert.equal(withNew.players[0].seatNumber, undefined, 'troca com jogador sem assento libera o antigo');
const initial = auditar(undefined, t, '2026-09-16T12:00:00Z');
assert.equal(initial.audit!.length, 1);
assert.equal(auditar(initial, { ...initial }).audit!.length, 1, 'sem ação não há evento');
const log = auditar(initial, sorted);
assert.equal(log.audit!.length, 2);
assert.ok(log.audit![1].changes.some(c => c.before === 'Sem assento' && c.after.includes('Mesa')));
const paid = auditar(log, { ...log, players: log.players.map(p => p.id === a.id ? { ...p, paymentStatus: 'confirmed' } : p) });
assert.ok(paid.audit!.at(-1)!.changes.some(c => c.before === 'A receber' && c.after === 'Pago'));
assert.deepEqual(JSON.parse(JSON.stringify(paid)).audit, paid.audit, 'histórico serializável');
let eliminated = eliminar(sorted, a.id);
eliminated = moverAssento(eliminated, b.id, a.tableNumber!, a.seatNumber!);
const undone = desfazerEliminacao(eliminated, a.id);
assert.equal(undone.players[0].seatNumber, undefined, 'retorno não duplica assento ocupado');
const twice = eliminar(eliminar(sorted, a.id), b.id);
assert.equal(desfazerEliminacao(twice, a.id), twice, 'undo fora de ordem bloqueado');
console.log('Assentos, trocas, desfazer e auditoria passaram.');
