export type Feature = {
  nome: string;
  resumo: string;
  beneficio: string;
  itens: [string, string][];
};

export const FEATURES: Feature[] = [
  { nome: 'Criação de mesas', resumo: 'Uma mesa com as regras da sua noite.', beneficio: 'Do encontro entre amigos ao evento com várias mesas, a organização começa do seu jeito.', itens: [
    ['Nome e buy-in livre', 'Defina o nome da mesa e qualquer valor de entrada, inclusive com centavos.'],
    ['Estruturas de blinds', 'Use Deep Stack, Regular, Turbo ou Hyper como sugestão, edite cada nível ou crie sua estrutura do zero.'],
    ['Intervalos e ante', 'Escolha a duração de cada nível, os intervalos, os valores de small blind, big blind e ante.'],
    ['Regras da casa', 'Configure reentradas, rebuys, add-ons, bounties, limites e o ritmo da noite.'],
    ['Biblioteca de configurações', 'Salve, duplique e compartilhe estruturas, conjuntos de fichas e tabelas de premiação por código.'],
    ['Calendário de noites', 'Organize data, horário, local e etapas em um calendário, com lembretes e integração com sua agenda.'],
    ['Convites e presença', 'Convide por link, código ou WhatsApp e acompanhe quem confirmou, está em dúvida ou não vai.'],
    ['Lista de espera', 'Organize vagas, desistências e entrada tardia sem perder a ordem dos participantes.'],
    ['Sorteio de assentos', 'Distribua os jogadores automaticamente ou escolha os lugares manualmente.'],
    ['Múltiplas mesas', 'Balanceie jogadores, mova participantes e desfaça mesas conforme o campo diminui.'],
    ['Identidade da mesa', 'Escolha cores, naipes, ícones, imagens, temas e identidade visual para cada grupo ou clube.'],
    ['Do início ao encerramento', 'Acompanhe preparação, início, andamento, aprovação dos resultados e fechamento da noite.'],
  ] },
  { nome: 'Relógio e blinds', resumo: 'O ritmo da noite, à vista de todos.', beneficio: 'Um relógio claro para a mesa inteira, com controle do organizador e acompanhamento dos jogadores.', itens: [
    ['Agora e a seguir', 'Veja tempo restante, nível, small blind, big blind, ante e o próximo nível.'],
    ['Um relógio por torneio', 'Troque de mesa preservando a estrutura, o nível e o tempo de cada torneio.'],
    ['Pausar e retomar', 'Pause, retome, avance ou volte um nível quando a mesa precisar.'],
    ['Tempo ao voltar', 'Ao desbloquear a tela ou reabrir o app, o relógio acompanha o tempo realmente decorrido.'],
    ['Modo TV e projetor', 'Exiba relógio, blinds, intervalos, jogadores restantes e premiação em tela cheia.'],
    ['Controle pelo celular', 'O organizador controla a noite enquanto a TV, o tablet e os jogadores acompanham.'],
    ['Sincronização ao vivo', 'Mantenha as telas alinhadas pelo mesmo tempo de referência, sem relógios correndo separados.'],
    ['Intervalos programados', 'Inclua pausas na estrutura e acompanhe o tempo de descanso até a retomada.'],
    ['Alertas visuais', 'Destaques nos segundos finais e na mudança de nível ajudam a perceber o próximo blind.'],
    ['Avisos sonoros e voz', 'Receba anúncios de mudança de nível, último minuto e início ou fim do intervalo.'],
    ['Hand-for-hand', 'Controle a bolha com rodadas sincronizadas e congelamento do relógio quando necessário.'],
    ['Shot clock', 'Acompanhe o tempo de decisão nas mesas que usam limite por ação.'],
    ['Atividades no celular', 'Acompanhe o torneio com notificações e Live Activities, incluindo Dynamic Island em aparelhos compatíveis.'],
    ['Tela ligada e baixo consumo', 'Mantenha a apresentação ativa, com opções de baixo consumo, contraste e movimento reduzido.'],
  ] },
  { nome: 'Ranking de liga', resumo: 'Uma história que continua na próxima noite.', beneficio: 'Transforme encontros soltos em uma liga com calendário, classificação e rivalidades.', itens: [
    ['Classificação automática', 'Reúna posições, pontos, pódio e resultados das noites encerradas.'],
    ['Pontuação da sua liga', 'Defina fórmulas, pontos por posição, participação, vitória, ITM e bônus por bounty.'],
    ['Temporadas e etapas', 'Organize campeonatos, calendário de etapas e várias ligas independentes.'],
    ['Melhor de N e descartes', 'Conte os melhores resultados, descarte as piores etapas e configure critérios de desempate.'],
    ['Ranking projetado', 'Acompanhe como a classificação pode mudar durante a noite, antes do resultado final.'],
    ['Perfil por jogador', 'Consulte participações, vitórias, prêmios, saldo, ITM e retorno sobre o investimento.'],
    ['Evolução e tendências', 'Compare desempenho por período, temporada, formato, mesa e local.'],
    ['Confrontos diretos', 'Veja resultados contra cada adversário e o histórico das rivalidades do grupo.'],
    ['Badges e conquistas', 'Reconheça vitórias, consistência, eliminações, marcos e destaques da temporada.'],
    ['Prêmios de temporada', 'Defina reconhecimentos e premiações para além de uma única noite.'],
    ['Página pública da liga', 'Compartilhe calendário, classificação, resultados, prêmios e acompanhamento ao vivo.'],
    ['Estatísticas por local', 'Compare noites e desempenho entre casas, clubes e outros ambientes de jogo.'],
    ['Enquetes e comunicados', 'Combine datas, regras e decisões do campeonato com o grupo.'],
  ] },
  { nome: 'Jogadores e entradas', resumo: 'Cada jogador encontra seu lugar.', beneficio: 'Da confirmação de presença à última eliminação, acompanhe quem está na noite e o que aconteceu.', itens: [
    ['Cadastro simples', 'Adicione participantes por nome, apelido, avatar e contato, sem complicar a entrada na mesa.'],
    ['Perfis sem duplicação', 'Identifique cadastros repetidos e reúna o histórico de uma mesma pessoa.'],
    ['Entradas e recompras', 'Registre buy-ins, reentradas, rebuys, add-ons e observações por jogador.'],
    ['Eliminação e colocação', 'Marque saídas, atribua posições e corrija uma eliminação registrada por engano.'],
    ['Painel do jogador', 'Veja assento, mesa, blinds, relógio, posição, premiação e avisos em um único lugar.'],
    ['Acesso por QR Code', 'Entre por QR Code, link, PIN ou magic link, sem precisar instalar um aplicativo.'],
    ['Movimentações de mesa', 'Receba avisos de troca de assento ou mesa e confirme que a mudança foi recebida.'],
    ['Permissões por função', 'Separe os acessos de anfitrião, co-host, organizador, participante e convidado.'],
    ['Equipe de operação', 'Distribua funções de proprietário, administrador, floor e dealer nos eventos maiores.'],
    ['Passagem de organização', 'Compartilhe o controle ou entregue a operação a outro anfitrião durante a noite.'],
    ['Confirmações de ações', 'Confira eliminações, pagamentos, premiações e encerramentos antes de concluir.'],
    ['Acompanhamento de convidados', 'Compartilhe uma visão somente de leitura para amigos e espectadores.'],
    ['Lembretes e avisos', 'Receba convites, confirmações de presença, anúncios e atualizações da noite.'],
  ] },
  { nome: 'Controle de pagamentos', resumo: 'A conta fecha sem conversa perdida.', beneficio: 'Entradas, pendências e acertos ficam reunidos, com um fechamento fácil de conferir e compartilhar.', itens: [
    ['Pago, pendente ou contestado', 'Acompanhe o estado de cada pagamento e confirme os valores recebidos.'],
    ['Total por jogador', 'Veja o valor devido por entradas, reentradas e add-ons.'],
    ['Pagamentos parciais', 'Registre pagamentos em partes, observações e o saldo que ainda falta acertar.'],
    ['Arrecadação da noite', 'Acompanhe o bolo, o total recebido e as pendências.'],
    ['Quem pagou quem', 'Mantenha um registro dos acertos entre jogadores e organizadores.'],
    ['Cash-in e cash-out', 'Registre entradas, saídas e saldos individuais nas noites de cash game.'],
    ['Acerto inteligente', 'Organize quem deve pagar quem e reduza a quantidade de transferências necessárias.'],
    ['Comprovantes por foto', 'Use a leitura de comprovantes para sugerir valor e destinatário, com conferência do organizador.'],
    ['Relatórios financeiros', 'Consulte saldos por pessoa, mesa, período, liga e temporada.'],
    ['Resumo no WhatsApp', 'Compartilhe um fechamento pronto com valores, pendências e transferências sugeridas.'],
    ['Avisos financeiros', 'Receba notificações de buy-ins, cash-outs e mudanças de pagamento.'],
    ['Histórico de alterações', 'Confira quem registrou ou corrigiu cada lançamento e recupere ações importantes.'],
  ] },
  { nome: 'Premiação e resultados', resumo: 'Do último pote ao resultado final.', beneficio: 'Organize formatos, acordos e premiações para encerrar a noite com os valores definidos.', itens: [
    ['Premiação automática', 'Distribua o bolo conforme o campo e confira os valores de cada posição.'],
    ['Percentuais ou valores fixos', 'Crie sua tabela de premiação ou escolha uma predefinição salva.'],
    ['Arredondamento correto', 'Mantenha a soma dos prêmios igual ao valor total da premiação.'],
    ['Acordos de chop', 'Proponha divisões de prêmio e registre a aceitação ou recusa dos jogadores.'],
    ['Calculadora de ICM', 'Compare divisões considerando fichas e faixas de premiação.'],
    ['Equity, pote e side pot', 'Confira probabilidades, potes paralelos e divisões em situações com vários all-ins.'],
    ['Cash game', 'Organize compras, saídas, saldos, várias mesas e lista de espera.'],
    ['Bounty e rebuys', 'Controle recompensas por eliminação, recompras, reentradas e add-ons.'],
    ['Satélites e multimesa', 'Configure diferentes formatos de torneio e eventos com vários campos.'],
    ['Campeão e posições', 'Identifique o vencedor, registre colocações e aprove os resultados finais.'],
    ['Pagamento dos prêmios', 'Registre quem recebeu cada prêmio e o que ainda precisa ser acertado.'],
    ['Página pública da noite', 'Compartilhe andamento, classificação, resultados e premiação por link.'],
    ['Resultado para compartilhar', 'Prepare o resumo com posições, eliminados, estatísticas e acertos para o grupo.'],
    ['Impressão da operação', 'Gere listas de assentos, participantes e premiação para acompanhar o evento.'],
  ] },
  { nome: 'Histórico e plataforma', resumo: 'Sua liga organizada, de um aparelho ao outro.', beneficio: 'Preserve resultados, configurações e finanças, com acesso e ferramentas que acompanham o crescimento do grupo.', itens: [
    ['Histórico completo', 'Consulte posições, prêmios, pagamentos e resultados de cada noite.'],
    ['Busca e filtros', 'Encontre mesas abertas e encerradas por nome, período, local ou formato.'],
    ['Conta e recuperação', 'Acesse seu perfil, recupere o acesso e gerencie as sessões da conta.'],
    ['Sincronização entre aparelhos', 'Reúna os dados da mesa nos dispositivos do anfitrião, da equipe e dos jogadores.'],
    ['Operação offline', 'Continue organizando a noite sem sinal e sincronize os registros quando a conexão voltar.'],
    ['Backup automático', 'Preserve os dados com backups no servidor e recuperação de versões anteriores.'],
    ['Restauração pontual', 'Recupere um estado específico do histórico e configure a retenção dos backups.'],
    ['Auditoria e desfazer', 'Veja autor, horário, valor anterior e valor novo de cada alteração importante.'],
    ['Importação e exportação', 'Importe e exporte jogadores, torneios, pagamentos, estruturas, ranking e resultados em CSV.'],
    ['Calendários e PDFs', 'Importe séries, agendas e estruturas de arquivos, com sugestões da IA para conferir.'],
    ['API e webhooks', 'Conecte o King’s Table a outras ferramentas e receba eventos nas suas integrações.'],
    ['Domínio e marca próprios', 'Personalize a página pública do clube com domínio, cores e identidade visual.'],
    ['Console de dealer e floor', 'Ofereça à equipe de operação um painel dedicado para eventos maiores.'],
    ['Idiomas, moedas e fusos', 'Escolha moeda, idioma, fuso horário e formatos de data e valores.'],
    ['Acessibilidade', 'Ajuste contraste, texto e movimento, com navegação por teclado e leitor de tela.'],
    ['Privacidade e dados', 'Gerencie sessões, exportação de dados pessoais, exclusão de conta e diagnósticos.'],
    ['Cloud, híbrido e on-premise', 'Adapte a infraestrutura à operação de clubes e organizações profissionais.'],
    ['Primeira mesa sem complicação', 'Encontre criação, jogadores, pagamentos e relógio em um fluxo curto e organizado.'],
  ] },
  { nome: 'Rainha IA e estudos', resumo: 'Aprenda com as mãos da sua própria história.', beneficio: 'Reúna decisões, análises e estudo para chegar à próxima mesa mais preparado.', itens: [
    ['Conversa com a Rainha', 'Explore posição, pot odds, MDF, 3-bet e estratégia com uma assistente de poker.'],
    ['Memória do jogador', 'Leve seu histórico, objetivos e evolução para conversas personalizadas.'],
    ['Análise de mãos', 'Revise ações, tamanhos de aposta, cartas e decisões depois da noite.'],
    ['Trilhas de estudo', 'Organize temas, exercícios e revisões conforme o que você quer melhorar.'],
    ['Registro e envio de cartas', 'Guarde mãos, envie cartas e preserve o contexto de cada jogada.'],
    ['VPIP e win rate', 'Acompanhe frequência de participação, resultados e tendências do seu jogo.'],
    ['Rabbit hunt e revisão', 'Registre cartas de revisão e explore cenários das mãos que terminaram antes do river.'],
    ['Histórico de mãos', 'Consulte e exporte as mãos registradas para estudar em outras ferramentas.'],
    ['IA para organizar a noite', 'Receba sugestões de estrutura, ritmo, premiação e lembretes conforme o grupo.'],
    ['Mesa online com voz e vídeo', 'Leve o encontro para uma mesa virtual com jogo integrado e comunicação entre os participantes.'],
  ] },
];

export const FEATURE_NAMES = FEATURES.map(feature => feature.nome);
